services:
  cas-db:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=cas
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=cas_db
  
    pgadmin:
      image: dpage/pgadmin4:latest
      ports:
        - 5050:80
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@example.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      depends_on:
        - cas-db

volumes:
  db_data:
    external: true