import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WebSocketProvider } from "@/contexts/WebSocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WebSocketProvider url={process.env.NEXT_PUBLIC_WEBSOCKET_URL || "ws://localhost:8081"}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </WebSocketProvider>
  );
}
