apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: Never
        image: prod-cas-backend1:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: POSTGRES_USER
          value: "postgis"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "mydb"
        - name: POSTGRES_HOST
          value: "postgis"
        - name: KAFKA_BROKER
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - protocol: TCP
    name: wsmobile
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: wsfrontend
    port: 8081
    targetPort: 8081
  selector:
    app: backend
