apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cas-sandiego.lab.students.cs.unibo.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 3000
  - host: cas-sandiego.lab.students.cs.unibo.it
    http:
      paths:
      - path: /ws-frontend
        pathType: Prefix
        backend:
          service:
            name: backend-lb
            port:
              number: 30443
      - path: /ws-mobile
        pathType: Prefix
        backend:
          service:
            name: backend-lb
            port:
              number: 8080
