apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /ws-mobile
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /ws-frontend
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8081