kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: front-port
    port: 8081
    targetPort: 8081
  - name: back-port
    port: 8080
    targetPort: 8080
