services:
  cas-db:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=cas
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=cas_db
    networks:
      - cas-network
  
  pgadmin:
     image: dpage/pgadmin4:latest
     ports:
       - 5050:80
     environment:
       - PGADMIN_DEFAULT_EMAIL=admin@example.com
       - PGADMIN_DEFAULT_PASSWORD=admin
     depends_on:
       - cas-db
     networks:
       - cas-network
  
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - cas-db
    networks:
      - cas-network

networks:
  cas-network: